
name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # step untuk download repo
    - uses: actions/checkout@v3

    #step untuk download java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # step untuk install browser
    - name: Setup Edge
      uses: browser-actions/setup-edge@v1.1.0

    # setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

    # execute gradlew command for running
    - name: Execute test
      run: ./gradlew WEBTest
